FROM python:3.10
RUN mkdir /code
#Adding Files.
COPY ./ /code/


RUN mkdir /code/data/ &&  mkdir /code/configuration/ && mkdir /code/pkl_point/

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


